name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: C++
            language: cpp
          - name: C
            language: c
          - name: Rust
            language: rust
          - name: x86 Assembly
            language: asm

    name: ${{ matrix.config.name }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extra dependencies (Rust)
        if: matrix.config.language == 'rust'
        run: rustup toolchain install stable-i686-pc-windows-msvc

      - name: Extra dependencies (x86 Assembly)
        if: matrix.config.language == 'asm'
        run: |
          choco install -y nasm
          echo "::add-path::C:\Program Files\NASM"

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          ccache-variant: ''
          configure-args: -DEXAMPLE_LANGUAGE=${{ matrix.config.language }}